export enum NotificationType {
  SENSOR_ALERT = 'SENSOR_ALERT',
  SYSTEM_INFO = 'SYSTEM_INFO',
  PRODUCT_DEMAND = 'PRODUCT_DEMAND',
  NEW_REVIEW = 'NEW_REVIEW',
  PRODUCT_OF_INTEREST = 'PRODUCT_OF_INTEREST',
  OFFER_OR_STOCK_CHANGE = 'OFFER_OR_STOCK_CHANGE',
}
